spring.application.name=crow

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/crow}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:carlos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:carlos}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
